[package]
name = "abc171"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
proconio = "*"
superslice = "*"
itertools = "*"
petgraph = "*"
num-integer = "*"
ac-library-rs = "*"

[profile.release]
lto = true
panic = 'abort'
