[package]
name = "abc350"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
proconio = "*"
superslice = "*"
itertools = "*"
petgraph = "*"

[profile.release]
lto = true
panic = 'abort'
